### ISSUE TITLE
Issues related to outdated files and links

### ISSUE THREAD

**Issue by fholgado** [mdorn/proose#2]
Hi there,

Had some issues getting this to work on OSX 10.6.

I had to download the latest version of JSoup (http://jsoup.org/download) 1.5.2 as well as redownload the MongoDB connector (http://code.google.com/p/mongodb-rhino/).

You should probably update the files and instructions :)

I'll keep you posted as I use this. Thanks so much for your work!

**Comment by mdorn** [comment]
Thanks for reporting this, fholgado -- I hadn't tried it on OSX, only on Ubuntu Linux.  What I really think I should do is just include the dependencies pre-built in the repo, then make sure it runs on both platforms.  I'll do that as soon as I have a spare moment.

**Comment by mdorn** [comment]
Added dependencies to repo, updated documentation.
