### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by ikmolbo** [mdorn/proose#3]
Hi,

Proose is exactly what I am looking for to help interact with Goose via an API. However, I have no experience with Java, Prudence etc. Would it be possible to see a brief step-by-step to getting all of this set up?

Thanks

**Comment by mdorn** [comment]
wriggle, thanks for your interest in proose -- this is a bit of a tall order, I guess, in the sense that getting a Java environment up and running on your machine would be quite a bit beyond the scope of what I'd provide as part of any proose documentation.  Once you've done that, though, the rest should be pretty straightforward.  Here's a link to the Prudence docs: http://threecrickets.com/prudence/manual/tutorial/
