### ISSUE TITLE
The article.topImage.imageSrc does not change with different URLs

### ISSUE THREAD

**Issue by manusis** [mdorn/proose#4]
After enabling the image fetching, I tried with few different URLs. 

```
              Public.config = register(Configuration, null, {'setEnableImageFetching': true})

               retval = {
                    "title": String(article.getTitle()),
                    "text": String(StringEscapeUtils.unescapeHtml(article.getCleanedArticleText())),
                    "image" : String(article.topImage.imageSrc)
               }
```

It returns the correct image for the first article but for subsequent articles, it returns the same image (from the first article).   The imageSrc somehow seems to be cached between multiple calls. Am I missing something here

Thanks,
Rajiv

**Comment by mdorn** [comment]
Sorry, I guess I made image fetching not a configurable option for a reason.  It's not something I needed when I wrote this.  If you figure it out, and want to submit a patch, I'd appreciate it.

**Comment by manusis** [comment]
Hi Matt,

First of all, thank you for your quick response. After your response, we tried a few things to make it work but those did not yield result. 

We even tried replacing the jar file of the goose library with the latest version (2.0.2) but that also did not work. After replacing the jar file, we keep getting the error "Function importClass must be called with a class; had "[JavaPackage com.gravity.goose.Configuration]" instead." even when the "com/gravity/goose/Configuration.class" exists in the new jar. 

At this point, we are completely stuck. I guess we do not know enough about Prudence or Goose to make the fix. My colleague arun also created another ticket related to the same issue. 

I will appreciate if you could guide us on how to fix image fetching in either the goose version (1.4.1) packaged with proose  or the latest goose version (2.0.2).

Thanks,
Rajiv
